[package]
name = "hk2017"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "HK2017 algorithm for computing EHZ capacity of convex polytopes"

[dependencies]
nalgebra = "0.33"
itertools = "0.14"
thiserror = "2.0"

[dev-dependencies]
approx = "0.5"
