[package]
name = "tube"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Tube algorithm for computing EHZ capacity of convex polytopes"

[dependencies]
nalgebra = "0.33"
thiserror = "2.0"

[dev-dependencies]
approx = "0.5"
hk2017 = { path = "../hk2017" }
