[package]
name = "rust_viterbo_algorithm"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_viterbo_geom = { path = "../geom" }
nalgebra = "0.32"
minilp = "0.2"
osqp = "1.0.1"

[dev-dependencies]
proptest = "1.4"
rand = "0.8"
rand_chacha = "0.3"
