[package]
name = "billiard"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Billiard algorithm for EHZ capacity of Lagrangian product polytopes"

[dependencies]
nalgebra = "0.33"
itertools = "0.13"
thiserror = "2"

[dev-dependencies]
approx = "0.5"
