[lint]
select = ["E9", "F63", "F7", "F82"]  # runtime errors / import errors / undefined names
ignore = ["E402"]  # allow imports anywhere in experiments
unfixable = ["E9", "F63", "F7", "F82"]

[format]
quote-style = "double"
line-ending = "lf"
indent-style = "space"
skip-magic-trailing-comma = true
