name = "docbuild"
version = "0.1.0"
reservoir = false
keywords = ["docs"]
packagesDir = "../.lake/packages"

[[require]]
name = "lean_viterbo"
path = ".."

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.25.0"
